### PR TITLE
Fix #6.

### LINKED ISSUE #6: Incorrect length calculation for content with multibyte symbols.
Try it with:
```js
{"name":"tajné jménoed25519","id":"QmSvTNE2Eo7SxRXjmEaZnE91cNpduKjYFBtd2LYC4Rsoeq"}
// content.length = 83
// Buffer.byteLength(content) = 85
```

Correct implementation (not optimized):
```js
const writeLoop = (fd, content, offset, cb) => {
    write(fd, content, offset, (err, bytesWritten) => {
        if (err) {
            cb(err);
            return;
        }

        const contentLength = Buffer.byteLength(content);
        if (bytesWritten < contentLength - offset) {
            writeLoop(fd, content, offset + bytesWritten, cb);
        } else {
            cb(null);
        }
    });
};
```

### PR DESCRIPTION
**Pull request by overphoenix**

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -5,9 +5,7 @@ const { join, dirname } = require('path')
 
 var counter = 0
 
-function id () {
-  return process.pid + '.' + counter++
-}
+const tmpFile = (path) => join(dirname(path), '.' + process.pid + '.' + counter++)
```
Comment (mcollina) [inline index.js]: Can you use a top level function, or just nothing?

Comment (overphoenix) [reply index.js]: Done.

**Review by mcollina — APPROVED** [review]
LGTM
